# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f22', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('short_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('httpurl', models.URLField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
